version: '3.8'

services:
  frontend:
    container_name: svelte_node
    build:
      context: .
    env_file:
      - .env.production
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
