version: '3.8'

env_file:
  - .env
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL:     ${VITE_API_BASE_URL}
      PUBLIC_API_BASE_URL:   ${PUBLIC_API_BASE_URL}
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      VITE_RECAPTCHA_SITE_KEY:  ${VITE_RECAPTCHA_SITE_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 