version: '3.8'

services:
  frontend:
    container_name: svelte_node
    build:
      context: .
      args:
        PUBLIC_API_BASE_URL: ${PUBLIC_API_BASE_URL}

    expose:
      - "3000"

    env_file:
      - .env
    environment:
      - PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL}
      - PUBLIC_GOOGLE_MAPS_API_KEY=${PUBLIC_GOOGLE_MAPS_API_KEY}
      - PUBLIC_RECAPTCHA_SITE_KEY=${PUBLIC_RECAPTCHA_SITE_KEY}

    restart: unless-stopped

    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
