version: '3.8'

services:
  frontend:
    container_name: svelte_node
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    # 运行时不再需要 PUBLIC_* 变量
    env_file:
      - .env.production  # 如果你的 SSR 代码里还用到，也可以继续读
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
