version: '3.8'


services:
  frontend:
    build: .
    ports:
      - "5173:80"
    env_file:
      - .env
    environment:
      VITE_API_BASE_URL:     ${VITE_API_BASE_URL}
      PUBLIC_API_BASE_URL:   ${PUBLIC_API_BASE_URL}
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      VITE_RECAPTCHA_SITE_KEY:  ${VITE_RECAPTCHA_SITE_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    # Add healthcheck